# mysql:
  # image: mysql:5.7
  # ports:
    # - "3306:3306"
  # environment:
    # - MYSQL_ROOT_PASSWORD=
    # - MYSQL_ALLOW_EMPTY_PASSWORD=true
    # - MYSQL_USER=petclinic
    # - MYSQL_PASSWORD=petclinic
    # - MYSQL_DATABASE=petclinic
  # volumes:
    # - "./conf.d:/etc/mysql/conf.d:ro"


version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
  jenkins:
    image: jenkins/jenkins:2.249.2-jdk11
    ports:
      - 8080:8080
    networks:
      - mynetwork
networks:
  mynetwork: